modLoader="javafml"
loaderVersion="${javafml_range}"
issueTrackerURL="${issue_tracker_url}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://api.modrinth.com/updates/${modrinth_project}/forge_updates.json?neoforge=only"
displayURL="https://modrinth.com/mod/${modrinth_project}"
logoFile="${mod_id}.png"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config = "mixins.${mod_id}.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

displayTest="MATCH_VERSION"

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE" # NONE/BEFORE/AFTER
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="hammerlib"
    mandatory=true
    versionRange="[${hl_version},)"
    ordering="AFTER"
    side="BOTH"
